---
- name: Install dependency packages
  become: yes
  package:
    name: "{{ guacamole_apt_install }}"
    state: present
- include_tasks: install_guacamole_client.yml
- include_tasks: install_guacamole_mysql_authentication.yml
- include_tasks: duo_2fa_auth.yml
  when: duo_2fa_enable is defined and duo_2fa_enable == true
- include_tasks: ldap_auth.yml
  when: ldap_auth_enable is defined and ldap_auth_enable == true
- include_tasks: totp_2fa_auth.yml
  when: totp_2fa_enable is defined and totp_2fa_enable == true
- include_tasks: configure_guacamole.yml
